// <auto-generated />
namespace DojoLoko.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Bagulhodavalidação2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Bagulhodavalidação2));
        
        string IMigrationMetadata.Id
        {
            get { return "201711212202195_Bagulho da validação 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
